### ISSUE TITLE
NPCs have Owner: None

### ISSUE THREAD

**Issue by Rhaine-au** [ItsKodas/Horizons-Universe#1]
Allows PCs to find any access panel and assign ownership to themselves without any resistance.

**Comment by ItsKodas** [comment]
Alright, I should have a fix for it, it is going to be really messy though.
It will require me manually editing all the saves to add factions & npc clients that have been deleted.
I'll have to stop all the servers to do this though.

**Comment by ItsKodas** [comment]
Alright, the fix I have implemented seems to have worked, I'll push everything across the other sectors and we should be good to go :)
![image](https://user-images.githubusercontent.com/43526329/130389206-45063fab-4e34-45dd-a251-4f7251d5224f.png)

**Comment by ItsKodas** [comment]
Issue has been fixed, the cause was a Utility Plugin (BobsUtils)
