### ISSUE TITLE
Asteroids not spawning as they should

### ISSUE THREAD

**Issue by Capitalism1939** [ItsKodas/Horizons-Universe#5]
I'm currently 20km out from Triton but I can't find any asteroids.
![Capture](https://user-images.githubusercontent.com/89458125/130609289-21bd7e59-e9b7-4cd7-84fd-f741e3658f54.PNG)
![Capture2](https://user-images.githubusercontent.com/89458125/130609422-aa0801a7-5e02-440e-b106-60da18476d23.PNG)

**Comment by ItsKodas** [comment]
This is a really big issue, there just doesn't seem to be any asteroids spawning really anywhere...

**Comment by ItsKodas** [comment]
An occasional loner but there really isn't anything
![image](https://user-images.githubusercontent.com/43526329/130814520-f4e06a4c-0227-4460-92bc-eb68442f8dc2.png)

**Comment by Capitalism1939** [comment]
Jesus, best of luck to you

**Comment by ItsKodas** [comment]
This issue doesn't seem to be something we can fix =/
